# Site wide configuration

title:            "Jerry D'Antonio"
locale:           en_US
#url:              http://jdantonio.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Jerry D'Antonio
  avatar: profile-200-px.png
  bio: "Husband, software developer, educator, Navy veteran, Catholic, progressive libertarian, contrarian, music-head, and Cleveland Bridge Builder. I proudly live in Akron, OH."
  email: "stumpjumper@gmail.com"
  disqus-shortname: jerrydantonio
  twitter: jerrydantonio
  facebook: jdantonio
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: jdantonio
  stackoverflow: 
  linkedin: jdantonio
  instagram: 
  #lastfm: stmpjmpr
  tumblr: 
  pinterest: 
  foursquare: 
  #steam: jdantonio
  dribbble: 
  youtube: 
  #soundcloud: jdantonio

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
